diag_script_info = True
diag_script_info@season = "DJF"
diag_script_info@box = "Gulf-of-Guinea"

; Style
diag_script_info@styleset = "CMIP5"

diag_script_info@latrange = (/ -2, 4/)      
diag_script_info@lonrange = (/ -8, 8/)   

diag_script_info@multi_model_mean = "y"
diag_script_info@supporting_gridlines = "y"
diag_script_info@x_gridlines = "n"
diag_script_info@y_gridlines = "n"

;diag_script_info@plottype_lbres = False
;diag_script_info@minmax = (/0, 1.6/)
