diag_script_info = True

; Style
diag_script_info@styleset = "CMIP5"

diag_script_info@season = "JJAS"
diag_script_info@latrange_basic = (/-20, 40/)
diag_script_info@lonrange_basic = (/30, 150/)

diag_script_info@cn_levels_mean_basic = (/2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25, 27.5, 30, 32.5/)
diag_script_info@cn_levels_mean_diff_basic = (/-15, -13, -11, -9, -7, -5, -3, -1, 1, 3, 5, 7, 9, 11, 13, 15/)

diag_script_info@cn_levels_stddev_basic = (/0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5/)
diag_script_info@cn_levels_stddev_diff_basic = (/-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7/)

diag_script_info@plottype_lbres = False

diag_script_info@my_region = "SA"
diag_script_info@use_for_contour = "speed"  ; 'speed', 'zonal' (ua) or 'meridional' (va)
