# codacy configuration file

---

engines:
    coverage:
        enabled: true
        exclude_paths: [
            'tests',
        ]
    pylint:
        enabled: true
        python_version: 3

exclude_paths: [
    'doc/sphinx/**',
    'esmvaltool/doc/sphinx/**',
    # cmor tables
    'esmvaltool/interface_scripts/cmip*-cmor-tables/**',
    # old stuff
    'backend/**',
    'diag_scripts/**',
    'interface_data/**',
    'interface_scripts/**',
    'main.py',
    'nml/**',
    'plot_scripts/**',
    'reformat_scripts/**',
    'variable_defs/**',
]
