# prospector configuration file

---

output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: false

pyroma:
    run: true

pep8:
    full: true

pep257:
    # disable rules that are allowed by the numpy convention
    # see https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/violations.py
    # and http://pydocstyle.readthedocs.io/en/latest/error_codes.html
    disable: ['D107', 'D203', 'D212', 'D213', 'D402', 'D413', 'D416']
