# prospector configuration file

---

output-format: grouped

strictness: veryhigh
doc-warnings: true
test-warnings: true
member-warnings: false

pyroma:
  run: true

pep8:
  full: true
  # ignore rules that conflict with ruff formatter
  # E203: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
  # E501: https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  # W503: https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
  disable: ['E203', 'E501', 'W503']

pep257:
  # disable rules that are allowed by the numpy convention
  # see https://github.com/PyCQA/pydocstyle/blob/master/src/pydocstyle/violations.py
  # and http://pydocstyle.readthedocs.io/en/latest/error_codes.html
  disable: ['D107', 'D203', 'D212', 'D213', 'D402', 'D413', 'D416']
