# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    post_checkout:
      # The ESMValTool repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      - git stash
    install:
      - pixi install --frozen
    post_install:
      - git stash pop
    build:
      html:
        - pixi run sphinx-build -T -W --keep-going -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
      pdf:
        - pixi run sphinx-build -T -b latex -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/pdf
        - cd $READTHEDOCS_OUTPUT/pdf
        - cat latexmkrc
        - latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=esmvaltool -interaction=nonstopmode

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
