# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    # try miniforge3 when available? see github.com/ESMValGroup/ESMValTool/issues/3779
    # DO NOT use mambaforge-*; that is currently sunsetted
    python: "miniconda-latest"
  jobs:
    post_checkout:
      # The ESMValTool repository is shallow i.e., has a .git/shallow,
      # therefore complete the repository with a full history in order
      # to allow setuptools-scm to correctly auto-discover the version.
      - git fetch --unshallow
      - git fetch --all
    pre_install:
      - git stash
    post_install:
      - git stash pop

# Declare the requirements required to build your docs
conda:
  environment:
    environment_python.yml

# Build documentation in the doc directory with Sphinx
sphinx:
  configuration: doc/sphinx/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
