###############################################################################
# User's configuration file for the ESMValTool
# Manuel Schlund
###############################################################################
---

# Destination directory where all output will be written
# Includes log files and performance stats.
#
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# PLEASE CHANGE
output_dir: ~/scratch/esmvaltool_output
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# Directory for storing downloaded climate data
download_dir: /work/bd0854/DATA/ESMValTool2/download

# Auxiliary data directory
# Used by some recipes to look for additional datasets.
auxiliary_data_dir: /work/bd0854/DATA/ESMValTool2/AUX

# Run at most this many tasks in parallel --- [null]/1/2/3/4/...
# Set to ``null`` to use the number of available CPUs. If you run out of
# memory, try setting max_parallel_tasks to ``1`` and check the amount of
# memory you need for that by inspecting the file ``run/resource_usage.txt`` in
# the output directory. Using the number there you can increase the number of
# parallel tasks again to a reasonable number for the amount of memory
# available in your system.
max_parallel_tasks: 4

# Disable automatic downloads --- [true]/false
# Disable the automatic download of missing CMIP3, CMIP5, CMIP6, CORDEX,
# and obs4MIPs data from ESGF by default. This is useful if you are working
# on a computer without an internet connection.
search_esgf: never

# Log level of the console --- debug/[info]/warning/error
# For much more information printed to screen set log_level to ``debug``.
log_level: info

# Exit on warning --- true/[false]
# # Only used in NCL diagnostic scripts.
exit_on_warning: false

# Plot file format --- [png]/pdf/ps/eps/epsi
output_file_type: ps

# Remove the ``preproc`` directory if the run was successful --- [true]/false
# By default this option is set to ``true``, so all preprocessor output files
# will be removed after a successful run. Set to ``false`` if you need those
# files.
remove_preproc_dir: false

# Use netCDF compression --- true/[false]
compress_netcdf: false

# Save intermediary cubes in the preprocessor --- true/[false]
# Setting this to ``true`` will save the output cube from each preprocessing
# step. These files are numbered according to the preprocessing order.
save_intermediary_cubes: false

# Path to custom ``config-developer.yml`` file
# This can be used to customise project configurations. See
# ``config-developer.yml`` for an example. Set to ``null`` to use the default.
config_developer_file: null

# Use a profiling tool for the diagnostic run --- [false]/true
# A profiler tells you which functions in your code take most time to run.
# Only available for Python diagnostics.
profile_diagnostic: false

# Rootpaths to the data from different projects
# This default setting will work if files have been downloaded by the
# ESMValTool via ``offline=False``. Lists are also possible. For site-specific
# entries and more examples, see below. Comment out these when using a
# site-specific path.
rootpath:
  CMIP3: /work/bd0854/DATA/ESMValTool2/CMIP3
  CMIP5: [
    /work/bd0854/DATA/ESMValTool2/CMIP5_DKRZ,
    /work/bd0854/DATA/ESMValTool2/download/cmip5/output1,
    /work/bd0854/DATA/ESMValTool2/download/cmip5/output2,
  ]
  CMIP6: [
    /work/bd0854/DATA/ESMValTool2/CMIP6_DKRZ,
    /work/bd0854/DATA/ESMValTool2/download/CMIP6,
  ]
  CORDEX: /work/ik1017/C3SCORDEX/data/c3s-cordex/output
  EMAC: [
    /work/id0853/b302019,
    /work/bd0854/b309141/emac,
  ]
  ICON: [
    /work/bd1179/experiments,
    /work/bd0854/b309141/icon_eval/data,
    /work/bd1179/b309170/icon-ml_models/icon-nn/experiments,
    /work/bd1179/b309170/icon-ml_models/icon-a-ml/experiments,
  ]
  OBS: [
    /work/bd0854/DATA/ESMValTool2/OBS,
  ]
  OBS6: [
    /work/bd0854/DATA/ESMValTool2/OBS,
  ]
  obs4MIPs: [
    /work/bd0854/DATA/ESMValTool2/OBS,
  ]
  ana4mips: [
    /work/bd0854/DATA/ESMValTool2/OBS,
  ]
  native6: [
    /work/bd0854/DATA/ESMValTool2/RAWOBS,
    /work/bd0854/DATA/ESMValTool2/OBS,
    /pool/data/ERA5,
  ]
  RAWOBS: /work/bd0854/DATA/ESMValTool2/RAWOBS
  default: ~/work

# Directory structure for input data --- [default]/ESGF/BADC/DKRZ/ETHZ/etc.
# This default setting will work if files have been downloaded by the
# ESMValTool via ``offline=False``. See ``config-developer.yml`` for
# definitions. Comment out/replace as per needed.
drs:
  CMIP3: DKRZ
  CMIP5: DKRZ
  CMIP6: DKRZ
  CORDEX: BADC
