# Conda build recipe
---

# Build commmand:
# conda build . -c conda-forge -c birdhouse

# Package version number
{% set version = "2.0a1" %}

package:
  name: esmvaltool
  version: {{ version }}

source:
  # Use these two lines to build a release:
  # git_rev: v{{ version }}
  # git_url: https://github.com/ESMValGroup/ESMValTool.git
  # Use this line instead of the above to test building without a release:
  path: .

build:
  # Increment the build number when building a new conda package of the same
  # esmvaltool version, reset to 0 when building a new version.
  number: 1
  script: |
      python setup.py install --single-version-externally-managed --record=/tmp/record.txt
      POST_LINK="${PREFIX}/bin/.esmvaltool-post-link.sh"
      cp -v ${RECIPE_DIR}/language_support.sh ${POST_LINK};
      chmod +x ${POST_LINK};

requirements:
  build:
    - git
    - python {{ python }}
    # Normally installed via pip:
    - setuptools_scm
  run:
    # esmvaltool
    - python
    - libunwind  #  specifically for Python3.7+
    - graphviz
    - iris
    - python-stratify
    # Normally installed via pip:
    - cartopy
    - cf_units
    - cython
    - eofs
    - esmpy
    - matplotlib<3
    - nc-time-axis
    - netCDF4
    - numba
    - numpy
    - pandas
    - pillow
    - prov
    - psutil
    - pydot
    - python-cdo
    - pyyaml
    - scikit-learn
    - shapely
    - six
    - vmprof
    - xarray
    - yamale  # in birdhouse channel
    - fiona
    - xlsxwriter
    # Multi language support:
    - ncl>=6.5.0
    - jasper!=1.900.31  # pinned NCL dependency
    - r-base
    - cdo

test:
  # TODO: add unit tests? This seems to require installing the tests
  imports:
    - esmvaltool
  commands:
    - esmvaltool -h

about:
  home: https://www.esmvaltool.org
  license: Apache License, Version 2.0
  license_file: LICENSE
