diag_script_info = True
diag_script_info@season = "SON"
diag_script_info@box = "India"

; Style
diag_script_info@styleset = "CMIP5"

diag_script_info@latrange = (/ 12, 20/)      
diag_script_info@lonrange = (/ 75, 80/)   

diag_script_info@multi_model_mean = "y"
diag_script_info@supporting_gridlines = "y"
diag_script_info@x_gridlines = "n"
diag_script_info@y_gridlines = "n"

;diag_script_info@plottype_lbres = False
;diag_script_info@minmax = (/0, 1.6/)


