FROM esmvalgroup/esmvalcore:latest

COPY . /esmvaltool
WORKDIR /esmvaltool

RUN conda env update -n base environment.yml
RUN pip install .[develop]
RUN Rscript esmvaltool/install/R/setup.R
RUN julia esmvaltool/install/Julia/setup.jl

# Clean ESMValTool
RUN pip uninstall esmvaltool -y
RUN rm -r /esmvaltool
