# To build this container, go to ESMValTool root folder and execute:
# docker build -t ${TAG_OF_YOUR_CHOICE} . -f docker/Dockerfile.dev
FROM continuumio/miniconda3

COPY . /src/ESMValTool
WORKDIR /src/ESMValTool

RUN conda update -y conda pip && conda env update --name base --file environment.yml && conda clean --all -y
RUN pip install . && pip cache purge
RUN apt install julia -y && esmvaltool install Julia
RUN esmvaltool install R
RUN pip uninstall esmvaltool -y

RUN esmvaltool -h

ENTRYPOINT ["esmvaltool"]
CMD ["-h"]
