diag_script_info = True

;; Used by: IAV_Confidence_Plot.ncl

diag_script_info@month = "M"      ;; "A" or "M"

diag_script_info@ncdf  = "default"

diag_script_info@tas_datapath = "~/CCMValTool/CMIP5_Data/OBS/Anav/cru_ts_3_00.1901.2006.tmp.nc"
diag_script_info@pre_datapath = "~/CCMValTool/CMIP5_Data/OBS/Anav/cru_ts_3_00.1901.2006.pre.nc"
diag_script_info@nbp_datapath = "~/CCMValTool/CMIP5_Data/OBS/Anav/NBP_JMA.2010_1985-2008.mask11.nc"
diag_script_info@gpp_datapath = "~/CCMValTool/CMIP5_Data/OBS/Anav/Monthly_MTE-GPP-GL_1982-2011.nc";Monthly_MTE_GPP_GL_Jung_2011.nc"
diag_script_info@lai_datapath = "~/CCMValTool/CMIP5_Data/OBS/Anav/BU-MODIS_LAI_MONTHLY_1deg.nc"

