# Full list of authors and references for the currently implemented
# diagnostics.
#
# Add new entries alphabetically (for authors) or at the end of the
# respective lists. Do not change the current entries!
#

authors:
  # Core Team (PI and core developers)
  eyring_veronika:
    name: Eyring, Veronika
    institute: DLR, Germany
    email: veronika.eyring@dlr.de
    orcid: https://orcid.org/0000-0002-6887-4885
  andela_bouwe:
    name: Andela, Bouwe
    institute: NLeSC, Netherlands
    email: b.andela@esciencecenter.nl
    orcid: https://orcid.org/0000-0001-9005-8940
  broetz_bjoern:
    name: Broetz, Bjoern
    institute: DLR, Germany
    email: bjoern.broetz@dlr.de
    orcid:
  demora_lee:
    name: de Mora, Lee
    institute: PML, UK
    email: ledm@pml.ac.uK
    orcid: https://orcid.org/0000-0002-5080-3149
  drost_niels:
    name: Drost, Niels
    institute: NLeSC, Netherlands
    email: n.drost@esciencecenter.nl
    orcid: https://orcid.org/0000-0001-9795-7981
  koldunov_nikolay:
    name: Koldunov, Nikolay
    institute: AWI, Germany
    email: nikolay.koldunov@awi.de
    orcid: https://orcid.org/0000-0002-3365-8146
  lauer_axel:
    name: Lauer, Axel
    institute: DLR, Germany
    email: axel.lauer@dlr.de
    orcid: https://orcid.org/0000-0002-9270-1044
  mueller_benjamin:
    name: Mueller, Benjamin
    institute: LMU, Germany
    email: b.mueller@iggf.geo.uni-muenchen.de
    orcid:
  predoi_valeriu:
    name: Predoi, Valeriu
    institute: URead, UK
    email: valeriu.predoi@ncas.ac.uk
    orcid: https://orcid.org/0000-0002-9729-6578
  righi_mattia:
    name: Righi, Mattia
    institute: DLR, Germany
    email: mattia.righi@dlr.de
    orcid: https://orcid.org/0000-0003-3827-5950
  schlund_manuel:
    name: Schlund, Manuel
    institute: DLR, Germany
    email: manuel.schlund@dlr.de
    orcid: https://orcid.org/0000-0001-5251-0158
  vegas-regidor_javier:
    name: Vegas-Regidor, Javier
    institute: BSC, Spain
    email: javier.vegas@bsc.es
    orcid: https://orcid.org/0000-0003-0096-4291
  zimmermann_klaus:
    name: Zimmermann, Klaus
    institute: SMHI, Sweden
    email: klaus.zimmermann@smhi.se
    orcid: https://orcid.org/0000-0003-3994-2057
  # Development team
  aerts_jerom:
    name: Aerts, Jerom
    institute: University of Delft, Netherlands
    orcid: https://orcid.org/0000-0003-0157-4818
  alidoost_sarah:
    name: Alidoost, Sarah
    institute: NLeSC, Netherlands
    orcid: https://orcid.org/0000-0001-8407-6472
  anav_alessandro:
    name: Anav, Alessandro
    institute: Univ. of Exeter, UK
    orcid: https://orcid.org/0000-0002-4217-7563
  andrews_oliver:
    name: Andrews, Oliver
    institute: Tyndall Centre, UK
    orcid: https://orcid.org/0000-0002-1921-475X
  arnone_enrico:
    name: Arnone, Enrico
    institute: ISAC-CNR, Torino, Italy
    orcid: https://orcid.org/0000-0001-6740-5051
  bellprat_omar:
    name: Bellprat, Omar
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0001-6434-1793
  berg_peter:
    name: Berg, Peter
    institute: SMHI, Sweden
    orcid: https://orcid.org/0000-0002-1469-2568
  bock_lisa:
    name: Bock, Lisa
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0001-7058-5938
  bojovic_dragana:
    name: Bojovic, Dragana
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0001-7354-1885
  cagnazzo_chiara:
    name: Cagnazzo, Chiara
    institute: CNR, Italy
    orcid: https://orcid.org/0000-0002-2054-0448
  camphuijsen_jaro:
    name: Camphuijsen, Jaro
    institute: NLeSC, Netherlands
    orcid: https://orcid.org/0000-0002-8928-7831
  capistrano_vinicius:
    name: Capistrano, Vinicius
    institute: INPE, Brazil
    orcid: https://orcid.org/0000-0001-8653-2312
  caron_louis-philippe:
    name: Caron, Louis-Philippe
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0001-5221-0147
  chen_jack:
    name: Chen, Jack
    institute: NCAR, USA
    orcid:
  cionni_irene:
    name: Cionni, Irene
    institute: ENEA, Italy
    orcid: https://orcid.org/0000-0002-0591-9193
  cortesi_nicola:
    name: Cortesi, Nicola
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0002-1442-9225
  crezee_bas:
    name: Crezee, Bas
    institute: ETH Zurich, Switzerland
    orcid: https://orcid.org/0000-0002-1774-1126
  mohr_christianwilhelm:
    name: Mohr, Christian Wilhelm
    institute: Cicero, Norway
    orcid: https://orcid.org/0000-0003-2656-1802
  davin_edouardleopold:
    name: Davin, Edouard Leopold
    institute: ETH Zurich, Switzerland
    orcid: https://orcid.org/0000-0003-3322-9330
  davini_paolo:
    name: Davini, Paolo
    institute: CNR-ISAC, Italy
    orcid: https://orcid.org/0000-0003-3389-7849
  docquier_david:
    name: Docquier, David
    institute: UC Louvain, Belgium
    orcid: 0000-0002-5720-4253
  ehbrecht_carsten:
    name: Ehbrecht, Carsten
    institute: DKRZ, Germany
    orcid:
  frank_franziska:
    name: Frank, Franziska
    institute: DLR, Germany
    orcid:
  fuckar_neven:
    name: Fuckar, Neven
    institute: BSC, Spain
    orcid:
  gainusa-bogdan_alina:
    name: Gainusa-Bogdan, Alina
    institute: France
    orcid: https://orcid.org/0000-0001-6147-1883
  gallego-elvira_belen:
    name: Gallego-Elvira, Belen
    institute: NERC, UK
    orcid: https://orcid.org/0000-0002-2328-0354
  galytska_evgenia:
    name: Galytska, Evgenia
    institute: IUP, Bremen
    orcid: https://orcid.org/0000-0001-6575-1559
  gettelman_andrew:
    name: Gettelman, Andrew
    institute: NCAR, USA
    orcid: https://orcid.org/0000-0002-8284-2599
  gier_bettina:
    name: Gier, Bettina
    institute: University of Bremen, Germany
    orcid:
  gottschaldt_klaus-dirk:
    name: Gottschaldt, Klaus-Dirk
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0002-2046-6137
  guemas_virginie:
    name: Guemas, Virginie
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0002-6340-3558
  hagemann_stefan:
    name: Hagemann, Stefan
    institute: MPI-M, Germany
    orcid: https://orcid.org/0000-0001-5444-2945
  hansson_ulf:
    name: Hansson, Ulf
    institute: SMHI, Sweden
    orcid:
  vonhardenberg_jost:
    name: von Hardenberg, Jost
    institute: ISAC-CNR, Torino, Italy
    orcid: https://orcid.org/0000-0002-5312-8070
  hassler_birgit:
    name: Hassler, Birgit
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0003-2724-709X
  hempelmann_nils:
    name: Hempelmann, Nils
    institute: IPSL, France
    orcid:
  hunter_alasdair:
    name: Hunter, Alasdair
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0001-8365-3709
  hutjes_ronald:
    name: Hutjes, Ronald
    institute: Univ. of Wageningen, NL
    orcid:
  juckes_martin:
    name: Juckes, Martin
    institute: BADC, UK
    orcid:
  kadygrov_nikolay:
    name: Kadygrov, Nikolay
    institute: IPSL, France
    orcid:
  kalverla_peter:
    name: Kalverla, Peter
    institute: NLeSC, Netherlands
    orcid: https://orcid.org/0000-0002-5025-7862
  kindermann_stephan:
    name: Kindermann, Stephan
    institute: DKRZ, Germany
    orcid: https://orcid.org/0000-0001-9335-1093
  krasting_john:
    name: Krasting, John
    institute: NOAA, USA
    orcid: https://orcid.org/0000-0002-4650-9844
  lejeune_quentin:
    name: Lejeune, Quentin
    institute: Climate Analytics, Germany
    orcid: https://orcid.org/0000-0001-9152-3197
  lembo_valerio:
    name: Lembo, Valerio
    institute: CEN, University of Hamburg, Germany
    orcid: https://orcid.org/0000-0001-6085-5914
  levine_richard:
    name: Levine, Richard
    institute: MetOffice, UK
    orcid: https://orcid.org/0000-0003-1210-0415
  little_bill:
    name: Little, Bill
    institute: MetOffice, UK
    orcid:
  lledo_llorenc:
    name: Lledo, Llorenc
    institute: BSC, Spain
    orcid:
  lorenz_ruth:
    name: Lorenz, Ruth
    institute: ETH Zurich, Switzerland
    orcid: https://orcid.org/0000-0002-3986-1268
  lovato_tomas:
    name: Lovato, Tomas
    institute: CMCC, IT
    orcid: https://orcid.org/0000-0002-5188-6767
  makela_jarmo:
    name: Makela, Jarmo
    institute: FMI, Finland
    orcid:
  maloney_eric:
    name: Maloney, Eric
    institute: Colorado State University, USA
    orcid: https://orcid.org/0000-0002-2660-2611
  manubens_nicolau:
    name: Manubens, Nicolau
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0002-0114-508X
  mason_erik:
    name: Mason, Erik
    institute: NOAA, USA
    orcid:
  sandstad_marit:
    name: Sandstad, Marit
    institute: Cicero, Norway
    orcid:
  massonnet_francois:
    name: Massonnet, Francois
    institute: Universite Catholique de Louvain, Belgium
    orcid:
  martin_gill:
    name: Martin, Gill
    institute: MetOffice, UK
    orcid: https://orcid.org/0000-0003-0851-6020
  mavilia_irene:
    name: Mavilia, Irene
    institute: ISAC-CNR, Bologna, Italy
    orcid: https://orcid.org/0000-0002-4938-2906
  mello_felipe:
    name: Mello, Felipe
    institute: INPE, Brazil
    orcid: https://orcid.org/0000-0002-8832-2869
  dalvi_mohit:
    name: Dalvi, Mohit
    institute: MetOffice, UK
    orcid: https://orcid.org/0000-0003-1669-0811
  nikulin_grigory:
    name: Nikulin, Grigory
    institute: SMHI, Sweden
    orcid: https://orcid.org/0000-0002-4226-8713
  nobre_paulo:
    name: Nobre, Paulo
    institute: INPE, Brazil
    orcid: https://orcid.org/0000-0001-9061-4556
  gonzalez-reviriego_nube:
    name: Gonzalez-Reviriego, Nube
    institute: BSC, Spain
    orcid: https://orcid.org/0000-0002-5919-6701
  oliveira_arildo:
    name: Oliveira, Arildo
    institute: INPE, Brazil
  pandde_amarjiit:
    name: Pandde, Amarjiit
    institute: Univ. of Arizona, USA
    orcid:
  perez-zanon_nuria:
    name: Perez-Zanon, Nuria
    institute: BSC, Spain
    orcid:
  pelupessy_inti:
    name: Pelupessy, Inti
    institute: Netherlands eScience Center
    orcid:
  phillips_adam:
    name: Phillips, Adam
    institute: NCAR, USA
    orcid: https://orcid.org/0000-0003-4859-8585
  pugh_thomas:
    name: Pugh, Thomas
    institute: KIT, Germany
    orcid:
  read_simon:
    name: Read, Simon
    institute: Univ. of Reading, UK
    orcid:
  ringer_mark:
    name: Ringer, Mark
    institute: MetOffice, UK
    orcid: https://orcid.org/0000-0003-4014-2583
  rio_catherine:
    name: Rio, Catherine
    institute: IPSL, France
    orcid: https://orcid.org/0000-0002-6590-7733
  roehrig_romain:
    name: Roehrig, Romain
    institute: MeteoFr, France
  russell_joellen:
    name: Russell, Joellen
    institute: Univ. of Arizona, USA
    orcid:
  senftleben_daniel:
    name: Senftleben, Daniel
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0002-3903-3841
  serva_federico:
    name: Serva, Federico
    institute: CNR, Italy
    orcid: https://orcid.org/0000-0002-7118-0817
  sommer_philipp:
    name: Sommer, Philipp
    institute: Univ. of Hamburg, Germany
    orcid:
  stacke_tobias:
    name: Stacke, Tobias
    institute: MPI-M, Germany
    orcid: https://orcid.org/0000-0003-4637-5337
  sterl_andreas:
    name: Sterl, Andreas
    institute: KNMI, Netherlands
    orcid: https://orcid.org/0000-0003-3457-0434
  swaminathan_ranjini:
    name: Swaminathan, Ranjini
    institute: University of Reading, UK
    orcid: https://orcid.org/0000-0001-5853-2673
  teichmann_claas:
    name: Teichmann, Claas
    institute: GERICS, Hamburg, Germany
    orcid:
  torralba_veronica:
    name: Torralba, Veronica
    institute: BSC, Spain
    orcid:
  tsushima_yoko:
    name: Tsushima, Yoko
    institute: MetOffice, UK
    orcid:
  vanulft_bert:
    name: van Ulft, Bert
    institute: KNMI, Netherlands
    orcid: https://orcid.org/0000-0001-8653-2312
  verhoeven_stefan:
    name: Verhoeven, Stefan
    institute: NLeSC, Netherlands
    orcid: https://orcid.org/0000-0002-5821-2060
  walton_jeremy:
    name: Walton, Jeremy
    institute: MetOffice, UK
    orcid: https://orcid.org/0000-0001-7372-178X
  wang_shiyu:
    name: Wang, Shiyu
    institute: SMHI, Sweden
    orcid:
  weigel_katja:
    name: Weigel, Katja
    institute: University of Bremen and DLR, Germany
    orcid: https://orcid.org/0000-0001-6133-7801
  wenzel_sabrina:
    name: Wenzel, Sabrina
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0001-5343-2446
  zechlau_sabrina:
    name: Zechlau, Sabrina
    institute: DLR, Germany
    orcid: https://orcid.org/0000-0001-5343-2446
  williams_keith:
    name: Williams, Keith
    institute: MetOffice, UK
    orcid:
  # Viewers (not active developers)
  balaji_venkatramani:
    name: Balaji, Venkatramani
    institute: GFDL, USA
    orcid:
  bunzel_felix:
    name: Bunzel, Felix
    institute: MPI-M, Germany
    orcid:
  charlton-perez_andrew:
    name: Charlton-Perez, Andrew
    institute: Univ. of Reading, UK
    orcid:
  corti_susanna:
    name: Corti, Susanna
    institute: ISAC-CNR, Torino, Italy
    orcid:
  dennis_john:
    name: Dennis, John
    institute: NCAR, USA
    orcid:
  graf_phoebe:
    name: Graf, Phoebe
    institute: DLR, Germany
    orcid:
  hegglin_michaela:
    name: Hegglin, Michaela
    institute: Univ. of Reading, UK
    orcid:
  hendricks_johannes:
    name: Hendricks, Johannes
    institute: DLR, Germany
    orcid:
  john_jasmin:
    name: John, Jasmin
    institute: NOAA, USA
    orcid:
  jones_colin:
    name: Jones, Colin
    institute: MetOffice, UK
    orcid:
  kaiser_christopher:
    name: Kaiser, Christopher
    institute: DLR, Germany
    orcid:
  karpechko_alexey:
    name: Karpechko, Alexey,
    institute: FMI, Finland
    orcid:
  lawrence_bryan:
    name: Lawrence, Bryan
    institute: STFC, UK
    orcid:
  mickelson_sheri:
    name: Mickelson, Sheri
    institute: NCAR, USA
    orcid:
  oconnor_fiona:
    name: OConnor, Fiona
    institute: MetOffice, UK
    orcid:
  radhakrishnan_aparna:
    name: Radhakrishnan, Aparna
    institute: GFDL, USA
    orcid:
  sellar_alistair:
    name: Sellar, Alistair
    institute: MetOffice, UK
    orcid:
  wyser_klaus:
    name: Wyser, Klaus
    institute: SMHI, Sweden
    orcid:
  # Former developers
  braeu_melanie:
    name: Braeu, Melanie
    institute: DLR, Germany
    orcid:
  duscha_christiane:
    name: Duscha, Christiane
    institute: DLR, Germany
    orcid:
  enright_clare:
    name: Enright, Clare
    institute: UEA, UK
    orcid:
  evaldsson_martin:
    name: Evaldsson, Martin
    institute: SMHI, Sweden
    orcid:
  haluszczynski_alexander:
    name: Haluszczynski, Alexander
    institute: DLR, Germany
    orcid:
  herman_michael:
    name: Herman, Michael
    institute: New Mexico Tech, USA
    orcid:
  huebner_michael:
    name: Huebner, Michael
    institute: DLR, Germany
    orcid:
  johnston_marston:
    name: Johnston, Marston
    institute: SMHI, Sweden
    orcid:
  klinger_carolin:
    name: Klinger, Carolin
    institute: DLR, Germany
    orcid:
  kolax_michael:
    name: Kolax, Michael
    institute: SMHI, Sweden
    orcid:
  kunert_dominik:
    name: Kunert, Dominik
    institute: DLR, Germany
    orcid:
  loew_alexander:
    name: Loew, Alexander
    institute: LMU, Germany
    orcid:
  neale_richard:
    name: Neale, Richard
    institute: NCAR, US
    orcid:
  orlowsky_boris:
    name: Orlowsky, Boris
    institute: ETH, Switzerland
    orcid:
  pascoe_stephen:
    name: Pascoe, Stephen
    institute: STFC, UK
    orcid:
  senftleben_daniel:
    name: Senftleben, Daniel
    institute: DLR, Germany
    orcid:
  stevens_mark:
    name: Stevens, Mark
    institute: NCAR, US
    orcid:
  # Former viewers (not active viewers)
  butchart_neal:
    name: Butchart, Neal
    institute: MetOffice, UK
    orcid:
  hassell_david:
    name: Hassell, David
    institute: Univ. of Reading, UK
    orcid:
  ivanova_detelina:
    name: Ivanova, Detelina
    institute: NERSC, Norway
    orcid:
  moise_aurel:
    name: Moise, Aurel
    institute: BOM, Australia
    orcid:
  pendlebury_diane:
    name: Pendlebury, Diane
    institute: Univ. of Toronto, Canada
    orcid:
  stepanova_daria:
    name: Stepanova, Daria
    institute: FMI, Finland
    orcid:
  tilmes_simone:
    name: Tilmes, Simone
    institute: NCAR, US
    orcid:

# Note: the reference section has been replaced by the folder esmvaltool/references that contains bibtex files.
# How to add a bibtex file to esmvaltool/references:
#  - make a bibtex file for a reference entry. There are some online tools to convert a doi to bibtex format like https://doi2bib.org/
#  - rename the file to the tag used in the recipe or diagnostic.
#  - add the file to the folder esmvaltool/references.

projects:
  applicate: EU Horizon 2020 Advanced prediction in polar regions and beyond
  c3s-magic: Copernicus Climate Change Service 34a Lot 2 (MAGIC) project
  climval: BMBF MiKlip Project ClimVal
  cmip6dicad: BMBF CMIP6 Project Germany
  cmug: ESA CMUG
  crescendo: EU H2020 project CRESCENDO
  dlrveu: DLR project VEU
  dlrveu2: DLR project VEU2
  embrace: EU FP7 project EMBRACE
  esmval: DLR project ESMVal
  eval4cmip: DLR and University of Bremen project funded by the Initiative and Networking Fund of the Helmholtz Society
  ewatercycle: eWaterCycle project
  primavera: EU H2020 project PRIMAVERA
  qa4ecv: QA4ECV
  russell_project: US Clivar, Ocean Carbon Biogeochemistry, ESGF, NOAA, NSF, NASA, US Antarctic program
  trr181: DFG Project TRR-181, Energy transfers in Atmosphere and Ocean
  ukesm: UKESM, UK Earth System Model project (NERC)

realms:
  aerosol: aerosol
  atmos: atmosphere
  atmosChem: atmospheric chemistry
  land: land
  landIce: land ice
  ocean: ocean
  ocnBgchem: ocean biogeochemistry
  seaIce: sea ice

themes:
  aerosols: aerosols
  atmDyn: atmospheric dynamics
  bgchem: biogeochemistry
  bgphys: biogeophysics
  carbon: carbon cycle
  chem: chemistry
  clouds: clouds
  EC: emergent constraint
  ghg: greenhouse gases
  monsoon: monsoons
  phys: physics
  seaIce: sea ice
  varmodes: modes of variability

domains:
  eq: equatorial
  et: extra tropics
  global: global
  midlat: mid-latitudes
  nh: northern hemisphere
  nhext: northern extra tropics
  nhmidlat: northern mid-latitudes
  nhpolar: northern polar
  nhtrop: northern tropics
  polar: polar
  reg: regional
  sh: southern hemisphere
  shext: southern extra tropics
  shmidlat: southern mid-latitudes
  shpolar: southern polar
  shtrop: southern tropics
  trop: tropics

plot_types:
  errorbar: error bar plot
  bar: bar chart
  circle: different overlapping circles
  diurn: diurnal cycle
  geo: geographical distribution
  histogram: histogram
  portrait: portrait diagram
  polar: polar-stereographic plot
  scatter: scatter plot
  seas: seasonal cycle
  sect: meridional section
  size: size-distribution
  vert: vertical profile
  taylor: taylor diagram
  times: time series
  zonal: zonal mean
  pro: profile  # (any other kind of line chart)
  box: boxplot
  other: other plot types

statistics:
  anomaly: anomaly
  corr: correlation
  diff: difference
  eof: empirical orthogonal function (EOF)
  mean: mean
  spectrum: spectrum
  stddev: standard deviation
  var: variability
  rmsd: rmsd
  range: range of values
  trend: temporal trend
  clim: climatology
  perc: percentiles
  median: median
  detrend: detrend
  smpi: single metric performance index statistics
  mder: multiple diagnostic ensemble regression
  mvi: model variability index
  other: other statistics
