# -*- coding: utf-8 -*-
#
# ESMValTool C3S_511 Report documentation build configuration file, created by
# sphinx-quickstart on Thu Feb  8 09:56:32 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
#import os
#import sys
#sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'ESMValTool C3S_511 Report'
copyright = u'2018, ESMValTool Development Team'
author = u'ESMValTool Development Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.1'
# The full version, including alpha/beta/rc tags.
release = u'0.1beta'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ESMValToolC3S_511Report'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
	\usepackage[section]{placeins}
        \usepackage{setspace}
        \usepackage{ragged2e}
	\usepackage{caption}
	\pagestyle{fancy}
	\extrafloats{1000}
        \renewcommand{\familydefault}{\sfdefault}
	''',

    # title page
    #
    'maketitle': r'''
        \begin{titlepage}
            \noindent\rule{\textwidth}{1pt}
            
            \vspace*{10mm} %%% * is used to give space from top
            \begin{flushright}\textbf{\Huge {ESMValTool C3S\_511 Report}}\end{flushright}
 	    \vspace*{10mm}
	    \begin{flushright} \doublespacing \textbf{\huge {++SUBREPORTTITLE++}}\end{flushright}
 
            \begin{flushright} \doublespacing \textbf{\huge {for ++VARIABLE++ from ++DATASET++}}\end{flushright}
	    
            \vspace*{25mm}
            \begin{flushright}\textbf{\textit{\Large {Release 0.1beta}}}\end{flushright}

            \vspace*{25mm}
            \begin{flushright}\textbf{\Large {ESMValTool Development Team}}\end{flushright}
            \vspace*{10mm}
            \begin{flushright}\textbf{\large {Created on: \today}}\end{flushright}
            \vspace*{10mm}

            \noindent\rule{\textwidth}{1pt}

            \vspace*{\fill}
            \begin{flushleft} \large \underline{Notification:}\end{flushleft}
 
            \begin{justify} \large This report was created with the ESMValTool v1.1.0$^1$ within the Copernicus Service C3S\_511 (grant number) for the Copernicus Climate Data Store. The following content must not be used for publications outside the Copernicus Service C3S\_511 or the Copernicus Climate Data Store.\end{justify}
 
            \begin{flushright} \small $^1$ Eyring et al., ESMValTool (v1.0) - a community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP, Geosci. Model Dev., 9, 1747-1802, https://doi.org/10.5194/gmd-9-1747-2016, 2016.\end{flushright}

        \end{titlepage}
        ''',

    # Latex figure (float) alignment
    #
    'figure_align': 'htbp',
    
    # Additional text for front page
    #
    #'atendofbody': 'test',
    #\begin{flushright}
    #\textbf{\textit{\underline{Notification:}}}\\
    #\large{This report was created with the ESMValTool v1.0\footnotemark within the Copernicus}\\
    #\large{Service C3S\_511 (grant number) for the Copernicus Climate Data Store.}\\
    #\large{The following content must not be used for publications outside the}\\
    #\large{Copernicus Service C3S\_511 or the Copernicus Climate Data Store.}\\
    #\footnotetext{Eyring et al., ESMValTool (v1.0) – a community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP, Geosci. Model Dev., 9, 1747-1802, https://doi.org/10.5194/gmd-9-1747-2016, 2016.}
    #\end{flushright}
    #''',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'ESMValToolC3S_511Report.tex','',
     'Notification:\\newline This report was created with the ESMValTool v1.1.0$^1$ within the Copernicus Service C3S\\_511 (grant number) for the Copernicus Climate Data Store. The following content must not be used for publications outside the Copernicus Service C3S\\_511 or the Copernicus Climate Data Store.\\newline $^1$ Eyring et al., ESMValTool (v1.0) - a community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP, Geosci. Model Dev., 9, 1747-1802, https://doi.org/10.5194/gmd-9-1747-2016, 2016.', 'howto'),
]




# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'esmvaltoolc3s_511report', u'ESMValTool C3S_511 Report',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ESMValToolC3S_511Report', u'ESMValTool C3S_511 Report',
     author, 'ESMValToolC3S_511Report', 'One line description of project.',
     'Miscellaneous'),
]



