def color_lookup(ecv_name):
    color_dict = {
        "default": dict({"default": "binary"}),
        "example": dict({"Data": "RdYlGn",
                         "Sequential":"YlGn",
                         "Diverging":"BrBG"}),
        "albdiffbnd": dict(),
        "albdirbnd": dict(),
        "albisccp": dict(),
        "burntArea": dict(),
        "cct": dict(),
        "cfc11": dict(),
        "cfc12": dict(),
        "clt": dict(),
        "cod": dict(),
        "hfds": dict(),
        "hur": dict(),
        "intdic": dict(),
        "lai": dict(),
        "lwp": dict(),
        "mrsos": dict(),
        "od550aer": dict(),
        "phnat": dict(),
        "pr": dict(),
        "reffclwtop": dict(),
        "rhs": dict(),
        "rlds": dict(),
        "rldscs": dict(),
        "rlus": dict(),
        "rluscs": dict(),
        "rlut": dict(),
        "rsds": dict(),
        "rsdscs": dict(),
        "rsdt": dict(),
        "rsus": dict(),
        "rsuscs": dict(),
        "rsut": dict(),
        "sf6": dict(),
        "sfcWind": dict(),
        "sftgif": dict(),
        "sic": dict(),
        "sidivvel": dict(),
        "sidmassdyn": dict(),
        "sidmassth": dict(),
        "siextentn": dict(),
        "siextents": dict(),
        "sispeed": dict(),
        "sit": dict(),
        "siu": dict(),
        "siv": dict(),
        "sm": dict(),
        "snc": dict(),
        "snd": dict(),
        "swe": dict(),
        "so": dict(),
        "spco2": dict(),
        "ta": dict(),
        "talknat": dict(),
        "tas": dict(),
        "tasmax": dict(),
        "tasmin": dict(),
        "tauuo": dict(),
        "tauvo": dict(),
        "tos": dict(),
        "toz": dict(),
        "tpf": dict(),
        "ts": dict(),
        "ua": dict(),
        "uas": dict(),
        "va": dict(),
        "vas": dict(),
        "vmrch4": dict(),
        "vmrco2": dict(),
        "vmrstrato3": dict(),
        "vmro3": dict(),
        "xco2": dict(),
        "xch4": dict(),
        "zos": dict(),
    }

    if ecv_name in color_dict.keys():
        if color_dict[ecv_name]:
            return color_dict[ecv_name]
        else:
            return color_dict["default"]
    else:
        return color_dict["default"]
