plot_type_info = True
plot_type_info@season = "JJAS"
plot_type_info@latrange = (/-20, 40/)
plot_type_info@lonrange = (/30, 150/)

plot_type_info@ref_model = (/"ERAINT"/)
plot_type_info@cn_levels_mean = (/2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25, 27.5, 30, 32.5/)
plot_type_info@cn_levels_mean_diff = (/-15, -13, -11, -9, -7, -5, -3, -1, 1, 3, 5, 7, 9, 11, 13, 15/)
plot_type_info@cn_levels_stddev = (/0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0/)
plot_type_info@cn_levels_stddev_diff = (/-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7/)

plot_type_info@plottype_lbres = False
