#!/bin/bash
#
# USAGE jasmin-env COMMAND
#
# ENVIRONMENT
#TODO: update docstring
#   MODULE_NAME         The name of the module to load
#   PYTHONPATH_PREPEND  The path to prepend to PYTHONPATH after loading the
#                       module
#   QUIET_MODE          Don't print confirmation messages
#
# OPTIONS
#   COMMAND             The command to execute with options
set -eu

# Must be run before importing numpy, see
# https://www-avd/sci/dask_best_practice/numpy-threads.html.
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export NUMEXPR_NUM_THREADS=1

# Ensure '~/.local' isn't added to 'sys.path'.
export PYTHONNOUSERSITE=True

# If PYTHONPATH_PREPEND has been set, prepend it to PYTHONPATH to extend the
# Python environment.
if [[ ! -z ${PYTHONPATH_PREPEND:-} ]]; then
    echo "[INFO] Prepending the following to PYTHONPATH: ${PYTHONPATH_PREPEND}"
    export PYTHONPATH=${PYTHONPATH_PREPEND}:${PYTHONPATH:-}
fi

WORKFLOW_RUN_BIN_DIR="${CYLC_WORKFLOW_RUN_DIR}/bin"
WORKFLOW_SHARE_BIN_DIR="${CYLC_WORKFLOW_SHARE_DIR}/cycle/bin"
ROSE_APP_BIN_DIR="${CYLC_WORKFLOW_RUN_DIR}/app/${ROSE_TASK_APP:-$CYLC_TASK_NAME}/bin"
CONTAINER=${ROSE_DATAC}/container/esmvaltool.sif

export SINGULARITY_BIND="/badc,/gws/nopw/j04/esmeval/obsdata-v2,/home/users"
export SINGULARITYENV_PROJ_DATA="/opt/conda/envs/esmvaltool/share/proj"
export SINGULARITYENV_APPEND_PATH="${WORKFLOW_RUN_BIN_DIR}:${WORKFLOW_SHARE_BIN_DIR}:${ROSE_APP_BIN_DIR}"

if [[ -z ${QUIET_MODE:-} ]]; then
    echo "[INFO] Using the ${MODULE_NAME} container"
fi

/usr/bin/time -v -o "${CYLC_TASK_LOG_ROOT}.time" singularity -q exec "${CONTAINER}" "$@"
