name: Full Development Test (Python)

# runs on a push on master and at the end of every day
on:
  push:
    branches:
    - master
    - ga_full_develop_test  # testing branch
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.8]  # latest stable for both esmvaltool and core
      fail-fast: false
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
      - name: Setup esmvalcore and esmvaltool in dev mode
        run: |
          conda --version
          git clone https://github.com/ESMValGroup/ESMValCore.git
          cd ESMValCore
          pip install -e .[develop]
          pytest -n 2 -m "not installation"
          cd ..
          git clone https://github.com/ESMValGroup/ESMValTool.git
          cd ESMValTool
          pip install -e .[develop]
          esmvaltool install R
          esmvaltool install Julia
          pytest -n 2 -m "not installation"
