name: Conda Base Install

# runs on a push on master and at the end of every day
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 4 * * *'

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      # fail-fast set to False allows all other tests
      # in the worflow to run regardless of any fail
      fail-fast: false
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: esmvalgroup,conda-forge
      - shell: bash -l {0}
        run: mkdir -p conda_install_linux_artifacts_python_${{ matrix.python-version }}
      - shell: bash -l {0}
        run: conda --version 2>&1 | tee conda_install_linux_artifacts_python_${{ matrix.python-version }}/conda_version.txt
      - shell: bash -l {0}
        run: which conda 2>&1 | tee conda_install_linux_artifacts_python_${{ matrix.python-version }}/conda_path.txt
      - shell: bash -l {0}
        run: python -V 2>&1 | tee conda_install_linux_artifacts_python_${{ matrix.python-version }}/python_version.txt
      - shell: bash -l {0}
        run: conda install esmvaltool 2>&1 | tee conda_install_linux_artifacts_python_${{ matrix.python-version }}/install.txt
      - shell: bash -l {0}
        run: esmvaltool --help
      - shell: bash -l {0}
        run: esmvaltool version 2>&1 | tee conda_install_linux_artifacts_python_${{ matrix.python-version }}/version.txt
      - name: Upload artifacts
        if: ${{ always() }}  # upload artifacts even if fail
        uses: actions/upload-artifact@v2
        with:
          name: Conda_Install_Linux_python_${{ matrix.python-version }}
          path: conda_install_linux_artifacts_python_${{ matrix.python-version }}

# uncomment from here when we have a testing environment on an OSX machine
# and we know that this should work
#
#  osx:
#    runs-on: "macos-latest"
#    strategy:
#      matrix:
#        python-version: [3.6, 3.7]  # 3.8.5 not working as of 07-Sep-2020; serious issues at env solving
#      fail-fast: false
#    name: OSX Python ${{ matrix.python-version }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#          miniconda-version: "latest"
#          channels: esmvalgroup,conda-forge
#      - shell: bash -l {0}
#        run: mkdir -p conda_install_osx_artifacts_python_${{ matrix.python-version }}
#      - shell: bash -l {0}
#        run: conda --version 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/conda_version.txt
#      - shell: bash -l {0}
#        run: which conda 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/conda_path.txt
#      - shell: bash -l {0}
#        run: python -V 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/python_version.txt
#      # ncurses needs to be from conda-forge and not main channel
#      # for now it's turned off since we're not testing R/Julia installs
#      # - shell: bash -l {0}
#      #   run: conda uninstall -y ncurses
#      # - shell: bash -l {0}
#      #   run: conda list ncurses
#      # - shell: bash -l {0}
#      #   run: conda install -y conda-forge::ncurses
#      # - shell: bash -l {0}
#      #   run: conda list ncurses
#      - shell: bash -l {0}
#        #run: conda install esmvaltool --no-update-deps 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/install.txt
#        run: conda install esmvaltool-python esmvaltool-ncl 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/install.txt
#      - shell: bash -l {0}
#        run: esmvaltool --help
#      - shell: bash -l {0}
#        run: esmvaltool version 2>&1 | tee conda_install_osx_artifacts_python_${{ matrix.python-version }}/version.txt
#      - name: Upload artifacts
#        if: ${{ always() }}  # upload artifacts even if fail
#        uses: actions/upload-artifact@v2
#        with:
#          name: Conda_Install_OSX_python_${{ matrix.python-version }}
#          path: conda_install_osx_artifacts_python_${{ matrix.python-version }}
