name: Test

# runs on a push on master and at the end of every day
on:
  push:
    branches:
    - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
      - shell: bash -l {0}
        run: mkdir -p test_linux_artifacts_python_${{ matrix.python-version }}
      - shell: bash -l {0}
        run: conda --version 2>&1 | tee test_linux_artifacts_python_${{ matrix.python-version }}/conda_version.txt
      - shell: bash -l {0}
        run: python -V 2>&1 | tee test_linux_artifacts_python_${{ matrix.python-version }}/python_version.txt
      - shell: bash -l {0}
        run: pip install -e .[develop] 2>&1 | tee test_linux_artifacts_python_${{ matrix.python-version }}/install.txt
      - shell: bash -l {0}
        run: esmvaltool install R
      - shell: bash -l {0}
        run: esmvaltool install Julia
      - shell: bash -l {0}
        run: pytest -n 2 -m "not installation" 2>&1 | tee test_linux_artifacts_python_${{ matrix.python-version }}/test_report.txt
      - name: Upload artifacts
        if: ${{ always() }}  # upload artifacts even if fail
        uses: actions/upload-artifact@v2
        with:
          name: Test_Linux_python_${{ matrix.python-version }}
          path: test_linux_artifacts_python_${{ matrix.python-version }}

# uncomment from here when we have a testing environment on an OSX machine
# and we know that this should work
#
#  osx:
#    runs-on: "macos-latest"
#    strategy:
#      matrix:
#        python-version: [3.6, 3.7]  # 3.8.5 poses serious issues with environment solving
#      fail-fast: false
#    name: OSX Python ${{ matrix.python-version }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          activate-environment: esmvaltool
#          environment-file: environment.yml
#          python-version: ${{ matrix.python-version }}
#          miniconda-version: "latest"
#          channels: conda-forge
#      - shell: bash -l {0}
#        run: mkdir -p test_osx_artifacts_python_${{ matrix.python-version }}
#      - shell: bash -l {0}
#        run: conda --version 2>&1 | tee test_osx_artifacts_python_${{ matrix.python-version }}/conda_version.txt
#      - shell: bash -l {0}
#        run: python -V 2>&1 | tee test_osx_artifacts_python_${{ matrix.python-version }}/python_version.txt
#      - shell: bash -l {0}
#        run: pip install -e .[develop] --use-feature=2020-resolver 2>&1 | tee test_osx_artifacts_python_${{ matrix.python-version }}/install.txt
#      # ncurses needs to be from conda-forge and not main channel
#      # for now it's turned off since we're not testing R/Julia installs
#      # - shell: bash -l {0}
#      #   run: conda install -y conda-forge::ncurses 2>&1 | tee test_osx_artifacts_python_${{ matrix.python-version }}/ncurses.txt
#      # - shell: bash -l {0}
#      #   run: esmvaltool install R
#      # - shell: bash -l {0}
#      #   run: esmvaltool install Julia
#      - shell: bash -l {0}
#        run: pytest -n 2 -m "not installation" 2>&1 | tee test_osx_artifacts_python_${{ matrix.python-version }}/test_report.txt
#      - name: Upload artifacts
#        if: ${{ always() }}  # upload artifacts even if fail
#        uses: actions/upload-artifact@v2
#        with:
#          name: Test_OSX_python_${{ matrix.python-version }}
#          path: test_osx_artifacts_python_${{ matrix.python-version }}
