# workflow that performs a validity check of CITATION.cff file
# authors: Abel S. Siqueira, Faruk Diblen, Jurriaan Spaaks GH: @abelsiqueira, @fdiblen, @jspaaks

name: CFF File Validator

on:
  push:
    paths:
      - CITATION.cff
  schedule:
    - cron: '0 0 1 * *'

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"
