name: Run Esmvalbot Test

on:
  push:
    branches:
      - cron_esmvalbot_test
  # scheduled once every week
  schedule:
    - cron: '0 4 */7 * *'

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  create-lock-file:
    name: run Esmvalbot
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create empty commit on branch
        run: |
          git config user.name 'Valeriu Predoi'
          git config user.email 'valeriu.predoi@gmail.com'
          git commit --allow-empty -m "create empty commit"
      # Automated PR where we run "@esmvalbot please run examples/recipe_python.yml"
      # as comment in the PR
      # see https://github.com/marketplace/actions/create-pull-request
      - name: Create Auto PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Empty commit
          # committer: Valeriu Predoi <valeriu.predoi@gmail.com>
          author: Valeriu Predoi <valeriu.predoi@gmail.com> # ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: run-esmvalbot
          delete-branch: true
          title: '[EsmvalbotTest] Run esmvalbot test'
          body: Automatic PR
          labels: |
            testing
            esmvalbot
            automatedPR
          assignees: valeriupredoi
          reviewers: valeriupredoi
          draft: false
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            "@esmvalbot please run examples/recipe_python.yml"
          pr_number: ${{env.PULL_REQUEST_NUMBER}}
