---
name: Install from Conda

# runs on a push on main and at the end of every day
on:
  push:
    branches:
      - main
      - pixi
  schedule:
    - cron: "0 4 * * *"

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  linux:
    runs-on: "ubuntu-latest"
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13"]
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    steps:
      - name: Install Micromamba
        run: "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      - name: Install ESMValTool
        run: micromamba create -n esmvaltool esmvaltool python=${{ matrix.python-version }}
      - name: Verify installation
        run: |
          micromamba activate esmvaltool
          pip check
          esmvaltool --help
          esmvaltool version
