---
name: Install from Conda

permissions: {}

# runs on a push on main and at the end of every day
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  esmvaltool-python:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - "3.12"
          - "3.13"
    name: Install esmvaltool-python with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
        with:
          environment-name: esmvaltool-python
          create-args: >-
            python=${{ matrix.python-version }}
            esmvaltool-python
      - name: Verify installation
        run: |
          pip check
          esmvaltool --help
          esmvaltool version
          esmvaltool recipes list
  esmvaltool:
    runs-on: "ubuntu-latest"
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    name: Install esmvaltool on Linux
    steps:
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476  # v3.0.0
        with:
          environment-name: esmvaltool
          create-args: esmvaltool
      - name: Verify installation
        run: |
          pip check
          esmvaltool --help
          esmvaltool version
          esmvaltool recipes list
