---
name: Install from Conda

# runs on a push on main and at the end of every day
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: bash -l {0}

jobs:
  esmvaltool-python:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.12", "3.13"]
    name: Install esmvaltool-python with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Install Micromamba
        run: |
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      - name: Install ESMValTool with only Python dependencies
        run: micromamba create -n esmvaltool esmvaltool-python python=${{ matrix.python-version }}
      - name: Verify installation
        run: |
          eval "$(micromamba shell activate esmvaltool)"
          pip check
          esmvaltool --help
          esmvaltool version
          esmvaltool recipes list
  esmvaltool:
    runs-on: "ubuntu-latest"
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    name: Install esmvaltool on Linux
    steps:
      - name: Install Micromamba
        run: |
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      - name: Install ESMValTool
        run: micromamba create -n esmvaltool esmvaltool
      - name: Verify installation
        run: |
          eval "$(micromamba shell activate esmvaltool)"
          pip check
          esmvaltool --help
          esmvaltool version
          esmvaltool recipes list
