name: Check Markdown links

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: 'link-checker-config.json'
        file-path: './README.md, ./CONTRIBUTING.md, ./CODE_OF_CONDUCT.md'
