# Action that runs the full development stack:
# Steps (Python-only):
# - creates esmvaltool conda environment and pip-installs esmvaltool
# - downloads latest main of esmvalcore and installs it in development mode
# - runs tests of esmvaltool
# Triggered by a push to main and nightly
---
name: Test in Full Development Mode

permissions: {}

# runs on a push on main and at the end of every day
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  linux:
    runs-on: "ubuntu-latest"
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e  # v0.9.4
        with:
          frozen: true
          environments: esmvalcore-dev
      - name: Check code quality
        run: pre-commit run -a
      - name: Run tests
        run: pytest -n 2 -m "not installation"
      - name: Upload artifacts
        if: ${{ always() }} # upload artifacts even if fail
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: Development_installation_test_reports
          path: test-reports
      - name: Check the command line interface
        run: |
          esmvaltool version
          esmvaltool -- --help
          esmvaltool develop compare -- --help
