# Action that runs the full development stack:
# Steps (Python-only):
# - creates esmvaltool conda environment and pip-installs esmvaltool
# - downloads latest main of esmvalcore and installs it in development mode
# - runs tests of esmvaltool
# Triggered by a push to main and nightly
---
name: Test in Full Development Mode

permissions: {}

# runs on a push on main and at the end of every day
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

# Required shell entrypoint to have properly configured bash shell
defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  linux:
    runs-on: "ubuntu-latest"
    if: github.repository == 'ESMValGroup/ESMValTool' # avoid GAs in forks
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11  # v0.9.6
        with:
          frozen: true
          environments: esmvalcore-dev
      - name: Check code quality
        run: pre-commit run -a
      - name: Run tests
        run: pytest -n 2 -m "not installation"
      - name: Upload artifacts
        if: ${{ always() }} # upload artifacts even if fail
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Development_installation_test_reports
          path: test-reports
      - name: Check the command line interface
        run: |
          esmvaltool version
          esmvaltool -- --help
          esmvaltool develop compare -- --help
